// supabase/functions/score-full/index.ts
// ══════════════════════════════════════════════════════════════════════════════
// Vizcast scoring edge function — Lookup Table v2
//
// Replaces the W-block additive formula with per-spot lookup tables derived
// from GradientBoosting models trained on 79,452 satellite observations.
//
// Scoring layers (in order):
//   1. BASE:    lookup tables (swell × rain × wind × SST) → NTU → score
//   2. OVERLAY: satellite turbidity, RTOFS current, tide, recovery, webcam
//   3. APP.JSX: spotSeasonal delta, spotBiasMultiplier (applied client-side)
//
// Lookup table formula:
//   ntu = interp(swell_table, swell_h, swell_p)
//         × interp(rain_table, effective_rain, days_since_rain)
//         + interp(wind_table, wind_onshore, wind_longshore)
//         + interp(sst_table, sst)
//   where effective_rain = rain_24h + river_flow_equiv
//
// All W-block parameters (w_swell, w_wind, w_rain, push_mult etc) are
// no longer used for scoring but remain in App.jsx for documentation.
// ══════════════════════════════════════════════════════════════════════════════

// ── Lookup tables — embedded directly (19.5 KB, no external fetch needed) ────
// Generated by build_lookup_tables_v2.py from regression_features_v2.csv
// Rebuild: python build_lookup_tables_v2.py  (in C:\Users\updan\Documents\Viscast\)
// Then paste the new JSON content here to redeploy.
import LOOKUP_RAW from "./vizcast_lookup_tables_v2.json" with { type: "json" };
const LOOKUP: Record<string, SpotTable> = LOOKUP_RAW.spots;

// ── Types ─────────────────────────────────────────────────────────────────────
interface GridDef {
  swell_h: number[];
  swell_p: number[];
  rain_24h: number[];
  days_since_rain: number[];
  wind_onshore: number[];
  wind_longshore: number[];
  sst: number[];
}

interface RiverConfig {
  gauges: string[];
  flow_median: number;
  flow_p90: number;
  flow_scale: number;
  best_lag: number;
  use_fnu: boolean;
  fnu_gauge: string | null;
}

interface SpotTable {
  label: string;
  coast: number;
  papa: number;
  depth_m: number;
  n_obs: number;
  ntu_median: number;
  sst_median: number;
  grids: GridDef;
  swell_table: number[][];
  rain_table: number[][];
  wind_table: number[][];
  sst_table: number[];
  river: RiverConfig | null;
}

// ── Interpolation helpers ─────────────────────────────────────────────────────
function interp1d(grid: number[], values: number[], x: number): number {
  if (x <= grid[0]) return values[0];
  if (x >= grid[grid.length - 1]) return values[values.length - 1];
  for (let i = 0; i < grid.length - 1; i++) {
    if (x >= grid[i] && x <= grid[i + 1]) {
      const t = (x - grid[i]) / (grid[i + 1] - grid[i]);
      return values[i] * (1 - t) + values[i + 1] * t;
    }
  }
  return values[values.length - 1];
}

function interp2d(
  gridX: number[], gridY: number[], table: number[][], x: number, y: number
): number {
  const cx = Math.max(gridX[0], Math.min(gridX[gridX.length - 1], x));
  const cy = Math.max(gridY[0], Math.min(gridY[gridY.length - 1], y));
  let xi = gridX.length - 2;
  for (let i = 0; i < gridX.length - 1; i++) {
    if (cx >= gridX[i] && cx <= gridX[i + 1]) { xi = i; break; }
  }
  let yi = gridY.length - 2;
  for (let i = 0; i < gridY.length - 1; i++) {
    if (cy >= gridY[i] && cy <= gridY[i + 1]) { yi = i; break; }
  }
  const tx = gridX[xi + 1] !== gridX[xi] ? (cx - gridX[xi]) / (gridX[xi + 1] - gridX[xi]) : 0;
  const ty = gridY[yi + 1] !== gridY[yi] ? (cy - gridY[yi]) / (gridY[yi + 1] - gridY[yi]) : 0;
  return table[xi][yi]     * (1 - tx) * (1 - ty)
       + table[xi + 1][yi] * tx       * (1 - ty)
       + table[xi][yi + 1] * (1 - tx) * ty
       + table[xi + 1][yi + 1] * tx   * ty;
}

// ── Wind decomposition ────────────────────────────────────────────────────────
function decomposeWind(
  wind_spd_kmh: number, wind_dir_deg: number, coast_bearing: number
): { onshore: number; longshore: number } {
  const diffRad = (wind_dir_deg - coast_bearing) * Math.PI / 180;
  return {
    onshore:   Math.max(0, wind_spd_kmh * Math.cos(diffRad)),
    longshore: wind_spd_kmh * Math.sin(diffRad),
  };
}

// ── River flow → effective rain equivalent ────────────────────────────────────
function riverFlowToRainEquiv(
  spotRiver: RiverConfig | null,
  riverFlows: Record<string, number[]> | null | undefined
): number {
  if (!spotRiver || !riverFlows) return 0;
  const lag = spotRiver.best_lag ?? 0;
  let total_flow = 0, n_gauges = 0;
  for (const gaugeId of (spotRiver.gauges ?? [])) {
    const flows = riverFlows[gaugeId];
    if (flows && flows[lag] != null && !isNaN(flows[lag])) {
      total_flow += flows[lag];
      n_gauges++;
    }
  }
  if (n_gauges === 0) return 0;
  const flow_above = Math.max(0, total_flow - (spotRiver.flow_median ?? 0));
  return Math.min(50, flow_above * (spotRiver.flow_scale ?? 0));
}

// ── FNU → rain equivalent ─────────────────────────────────────────────────────
function riverFnuToRainEquiv(
  spotRiver: RiverConfig | null,
  riverFnus: Record<string, number[]> | null | undefined
): number {
  if (!spotRiver || !riverFnus || !spotRiver.use_fnu || !spotRiver.fnu_gauge) return 0;
  const lag = spotRiver.best_lag ?? 0;
  const fnus = riverFnus[spotRiver.fnu_gauge];
  if (!fnus || fnus[lag] == null || isNaN(fnus[lag])) return 0;
  const fnu = fnus[lag];
  if (fnu < 10) return 0;
  return Math.min(40, fnu * 0.2);
}

// ── NTU → score ───────────────────────────────────────────────────────────────
const NTU_BP: [number, number][] = [
  [0, 100], [2, 90], [5, 75], [10, 58], [20, 40], [40, 22], [80, 10], [150, 0],
];
function ntuToScore(ntu: number): number {
  if (ntu <= NTU_BP[0][0]) return NTU_BP[0][1];
  if (ntu >= NTU_BP[NTU_BP.length - 1][0]) return NTU_BP[NTU_BP.length - 1][1];
  for (let i = 0; i < NTU_BP.length - 1; i++) {
    if (ntu >= NTU_BP[i][0] && ntu <= NTU_BP[i + 1][0]) {
      const t = (ntu - NTU_BP[i][0]) / (NTU_BP[i + 1][0] - NTU_BP[i][0]);
      return Math.round(NTU_BP[i][1] * (1 - t) + NTU_BP[i + 1][1] * t);
    }
  }
  return 0;
}

// ── Spot name → ID mapping ────────────────────────────────────────────────────
// Handles both spot_id strings and display names from App.jsx
const SPOT_NAME_MAP: Record<string, string> = {
  "nga_motu":                              "nga_motu",
  "Nga Motu — Inshore (Port Taranaki)":   "nga_motu",
  "motumahanga":                           "motumahanga",
  "Motumahanga (Saddleback Is.)":          "motumahanga",
  "fin_fuckers":                           "fin_fuckers",
  "Fin Fuckers (Cape Egmont / Warea)":     "fin_fuckers",
  "opunake":                               "opunake",
  "Opunake":                               "opunake",
  "patea_inshore":                         "patea_inshore",
  "Patea — Inshore":                       "patea_inshore",
  "patea_offshore":                        "patea_offshore",
  "Patea — Offshore Trap":                 "patea_offshore",
  "metal_reef":                            "metal_reef",
  "Boarfish Rock":                         "metal_reef",
  "The Metal Reef":                        "metal_reef",
  "kapiti_west":                           "kapiti_west",
  "Kāpiti West Face":                      "kapiti_west",
  "Kapiti West":                           "kapiti_west",
  "tokahaki":                              "tokahaki",
  "Tokahaki (North Tip)":                  "tokahaki",
  "aeroplane_island":                      "aeroplane_island",
  "Aeroplane Island (Tokomapuna)":         "aeroplane_island",
  "Aeroplane Island":                      "aeroplane_island",
  "rgv_reef":                              "rgv_reef",
  "RGV Reef":                              "rgv_reef",
  "the_aquarium":                          "the_aquarium",
  "The Aquarium":                          "the_aquarium",
};

function resolveSpotId(spot: Record<string, unknown>): string | null {
  const candidates = [
    spot.spot_id, spot.id, spot.name,
    (spot.W as Record<string, unknown> | undefined)?.spot_id,
  ];
  for (const c of candidates) {
    if (typeof c === "string") {
      const resolved = SPOT_NAME_MAP[c] ?? (LOOKUP[c] ? c : null);
      if (resolved) return resolved;
    }
  }
  return null;
}

// ── Days since rain helper ────────────────────────────────────────────────────
function calcDaysSinceRain(rainHistory: number[] | undefined, rain24h: number): number {
  if (rain24h > 2) return 0;
  if (!rainHistory || rainHistory.length === 0) return 7;
  for (let i = 0; i < rainHistory.length; i++) {
    if ((rainHistory[i] ?? 0) > 2) return i;
  }
  return Math.min(14, rainHistory.length);
}

// ── Plume reach ───────────────────────────────────────────────────────────────
function plumeReachFactor(rainHistory: number[] | undefined): number {
  if (!rainHistory || rainHistory.length === 0) return 0;
  const rain3d = rainHistory.slice(0, 3).reduce((a, b) => a + b, 0);
  const rain7d  = rainHistory.slice(0, 7).reduce((a, b) => a + b, 0);
  if (rain3d > 80) return 1.0;
  if (rain3d > 50) return 0.7;
  if (rain3d > 30) return 0.4;
  if (rain7d > 100) return 0.5;
  if (rain7d > 60)  return 0.3;
  return 0;
}

// ── CORS headers ──────────────────────────────────────────────────────────────
const HEADERS = {
  "Content-Type":                "application/json",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control":               "public, max-age=300",
};

// ── Main handler ──────────────────────────────────────────────────────────────
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: HEADERS });
  }

  try {
    const { cond, spot, W: _W } = await req.json();

    // ── Resolve spot ───────────────────────────────────────────────────────
    const sid = resolveSpotId(spot);
    if (!sid) {
      return new Response(JSON.stringify({
        score: 50, predicted_ntu: 5, plumeReach: 0,
        factors: { drivers: ["Unknown spot — fallback score"] },
        model: "lookup-v2-fallback",
      }), { headers: HEADERS });
    }

    const spotTable = LOOKUP[sid];
    if (!spotTable) {
      return new Response(JSON.stringify({
        score: 50, predicted_ntu: 5, plumeReach: 0,
        factors: { drivers: [`No table for ${sid}`] },
        model: "lookup-v2-fallback",
      }), { headers: HEADERS });
    }

    const grids = spotTable.grids;
    const coast = (spot?.W as Record<string, unknown> | undefined)?.coast_bearing
      ? Number((spot.W as Record<string, unknown>).coast_bearing)
      : spotTable.coast;

    // ── Unpack cond ────────────────────────────────────────────────────────
    const h = (cond.hist22 ?? {}) as Record<string, number[]>;
    const rainHistory: number[] = h.rain ?? [];
    const swellHist: number[]   = h.swell_h ?? [];

    const rain24h       = Number(cond.rain_24h ?? rainHistory[0] ?? 0);
    const swell_h       = Number(cond.swell_h  ?? swellHist[0]  ?? 0.5);
    const swell_p       = Number(cond.swell_p  ?? cond.swell_period ?? 8);
    const wind_kmh      = Number(cond.wind_spd ?? cond.wind_kmh ?? 0);
    const wind_dir      = Number(cond.wind_dir ?? 270);
    const sst           = Number(cond.sst ?? spotTable.sst_median ?? 18);
    const days_since_rain = calcDaysSinceRain(rainHistory, rain24h);

    // ── 1. Base NTU from swell ─────────────────────────────────────────────
    const base_ntu = Math.max(0.1, interp2d(
      grids.swell_h, grids.swell_p, spotTable.swell_table,
      Math.max(0.1, swell_h), Math.max(4, swell_p)
    ));

    // ── 2. Effective rain = rain_24h + river equivalent ────────────────────
    const river_flow_equiv = riverFlowToRainEquiv(
      spotTable.river, cond.riverFlows as Record<string, number[]> | null
    );
    const river_fnu_equiv = riverFnuToRainEquiv(
      spotTable.river, cond.riverFnus as Record<string, number[]> | null
    );
    const river_rain_equiv = Math.max(river_flow_equiv, river_fnu_equiv);
    const effective_rain   = Math.min(75, rain24h + river_rain_equiv);

    // ── 3. Rain multiplier (papa-scaled baked in) ──────────────────────────
    const rain_mult = Math.max(0.5, interp2d(
      grids.rain_24h, grids.days_since_rain, spotTable.rain_table,
      effective_rain, Math.max(0, Math.min(14, days_since_rain))
    ));

    // ── 4. Wind additive ───────────────────────────────────────────────────
    const { onshore, longshore } = decomposeWind(wind_kmh, wind_dir, coast);
    const wind_adj = interp2d(
      grids.wind_onshore, grids.wind_longshore, spotTable.wind_table,
      onshore, longshore
    );

    // ── 5. SST additive ───────────────────────────────────────────────────
    const sst_adj = interp1d(grids.sst, spotTable.sst_table, sst);

    // ── 6. Base NTU ───────────────────────────────────────────────────────
    let final_ntu = Math.max(0, base_ntu * rain_mult + wind_adj + sst_adj);

    // ── 7. Satellite overlay (MODIS/S2 turbidity, decays over 3 days) ─────
    let sat_adj = 0;
    if (cond.satTurbidity != null) {
      const satAge  = Number(cond.satDataAge ?? 0);
      const sat_ntu = Number(cond.satTurbidity) / 10;
      const decay   = Math.max(0, 1 - satAge / 3);
      sat_adj = (sat_ntu - final_ntu) * 0.35 * decay;
      final_ntu += sat_adj;
    }

    // ── 8. River FNU legacy adjustment (if no structured flow data) ────────
    let river_fnu_adj = 0;
    if (cond.riverTurbScore != null && river_rain_equiv === 0) {
      const river_impact = Number(spot?.river_impact ?? 0.3);
      river_fnu_adj = (Number(cond.riverTurbScore) / 100) * 8 * river_impact;
      final_ntu += river_fnu_adj;
    }

    final_ntu = Math.max(0, Math.min(150, final_ntu));
    let score = ntuToScore(final_ntu);

    // ── 9. RTOFS current adjustment — coast-relative decomposition ────────────
    // Task A: decompose current into coast-relative axes using spot's coast_bearing.
    //   onshore_current > 0: water pushed onto coast → increases turbidity
    //   longshore_current: Cook Strait squeeze / Patea bight flushing direction
    // coast_bearing values (degrees from north, direction coast faces):
    //   Nga Motu 290, Motumahanga 280, Fin Fuckers 265, Opunake 255
    //   Patea Inshore 220, Patea Offshore 225, Kapiti spots 275, SPI 270
    // Stored in spotTable.coast (generated by build_lookup_tables_v2.py).
    let current_adj = 0;
    let onshore_cur = 0, longshore_cur = 0;
    if (cond.current_vel != null && cond.current_dir != null) {
      const cur_vel = Number(cond.current_vel);
      const cur_dir = Number(cond.current_dir);
      const coastRad = coast * Math.PI / 180;

      // Reconstruct east (u) and north (v) components from speed and direction
      const cur_u = cur_vel * Math.sin(cur_dir * Math.PI / 180);
      const cur_v = cur_vel * Math.cos(cur_dir * Math.PI / 180);

      onshore_cur   = cur_u * Math.sin(coastRad) + cur_v * Math.cos(coastRad);
      longshore_cur = cur_u * Math.cos(coastRad) - cur_v * Math.sin(coastRad);

      const W_merged = { ..._W, ...(spot?.W as object ?? {}) };

      // Task B: taper current contribution when RTOFS data is stale.
      // 3 RTOFS model cycles at 3 hours each = 9 hours is the staleness threshold.
      const ageHrs = Number(cond.current_age_hrs ?? 0);
      const currentWeight = ageHrs <= 6 ? 1.0 : Math.max(0.3, 1 - (ageHrs - 6) / 18);

      // Onshore flow pushes sediment onto coast (penalty); offshore = clean flush (bonus)
      if (onshore_cur > 0) {
        current_adj = -onshore_cur * Number(W_merged?.cur_south ?? 12);
      } else {
        current_adj = -onshore_cur * Number(W_merged?.cur_north ?? 8);
      }

      // Task C: bight_mult amplifies onshore penalty scaled by swell height.
      // This makes the bight interaction a product of both signals (not a simple sum):
      // penalty ∝ onshore_current × swell_height, so both must be elevated to trigger.
      const bight_mult = Number((spot as Record<string, unknown>)?.bight_mult ?? W_merged?.bight_mult ?? 1.5);
      if (onshore_cur > 0) {
        // each 1 m of swell above 1 m adds 30% to the onshore penalty
        const swellFactor = Math.max(1.0, 1.0 + (swell_h - 1.0) * 0.3);
        current_adj *= bight_mult * swellFactor;
      }

      current_adj *= currentWeight;
      current_adj = Math.max(-20, Math.min(15, current_adj));
      score += current_adj;
    }

    // ── 10. Tide adjustment ────────────────────────────────────────────────
    let tide_adj = 0;
    if (cond.tide_h != null) {
      const W_merged = { ..._W, ...(spot?.W as object ?? {}) };
      const tide_sensitive = Number((spot as Record<string, unknown>)?.tide_sensitive ?? 0.3);
      const tide_h = Number(cond.tide_h);
      tide_adj = (tide_h - 1.0) * Number(W_merged?.tide_mult ?? 2) * tide_sensitive;
      tide_adj = Math.max(-8, Math.min(8, tide_adj));
      score += tide_adj;
    }

    // ── 11. Recovery bonus (consecutive clean days) ────────────────────────
    let recovery_adj = 0;
    if (days_since_rain >= 3 && (swellHist[0] ?? 0) < 1.5) {
      recovery_adj = Math.min(8, (days_since_rain - 2) * 1.5);
      score += recovery_adj;
    }

    // ── 12. Webcam adjustment ─────────────────────────────────────────────
    let webcam_adj = 0;
    if (cond.webcamTurbidity != null) {
      const webcam_ntu = Number(cond.webcamTurbidity) / 10;
      webcam_adj = (ntuToScore(webcam_ntu) - score) * 0.25;
      score += webcam_adj;
    }

    // ── Final clamp ───────────────────────────────────────────────────────
    score = Math.max(0, Math.min(100, Math.round(score)));

    // ── Plume reach ───────────────────────────────────────────────────────
    const plumeReach = plumeReachFactor(rainHistory);

    // ── Factors for UI display ─────────────────────────────────────────────
    const drivers: string[] = [];
    if (effective_rain > 5)  drivers.push(`rain×${rain_mult.toFixed(1)}`);
    if (wind_adj > 2)        drivers.push(`wind+${wind_adj.toFixed(1)}NTU`);
    if (base_ntu > 5)        drivers.push(`swell${swell_h.toFixed(1)}m`);
    if (Math.abs(sat_adj) > 1) drivers.push(`sat${sat_adj > 0 ? "+" : ""}${sat_adj.toFixed(1)}`);
    if (Math.abs(current_adj) > 2) drivers.push(onshore_cur > 0 ? "onshore-current" : "offshore-current");

    const factors = {
      drivers,
      base_ntu:          Math.round(base_ntu * 10) / 10,
      rain_mult:         Math.round(rain_mult * 100) / 100,
      wind_adj:          Math.round(wind_adj * 10) / 10,
      sst_adj:           Math.round(sst_adj * 10) / 10,
      sat_adj:           Math.round(sat_adj * 10) / 10,
      current_adj:       Math.round(current_adj * 10) / 10,
      current_onshore:   Math.round(onshore_cur * 100) / 100,
      current_longshore: Math.round(longshore_cur * 100) / 100,
      tide_adj:          Math.round(tide_adj * 10) / 10,
      recovery_adj:      Math.round(recovery_adj * 10) / 10,
      effective_rain:    Math.round(effective_rain * 10) / 10,
      river_rain_equiv:  Math.round(river_rain_equiv * 10) / 10,
      wind_onshore:      Math.round(onshore),
      wind_longshore:    Math.round(longshore),
      swell_h, swell_p, sst, days_since_rain,
      rain_7d: Math.round(rainHistory.slice(0, 7).reduce((a, b) => a + b, 0)),
    };

    // ── DEBUG: full breakdown for nga_motu / motumahanga inversion diagnosis ──
    if (sid === "nga_motu" || sid === "motumahanga") {
      console.log(
        `[DEBUG-INVERSION] ${sid} | ` +
        `swell=${swell_h.toFixed(2)}m/${swell_p}s | ` +
        `rain24h=${rain24h.toFixed(1)}mm dsr=${days_since_rain}d | ` +
        `wind=${wind_kmh.toFixed(0)}km/h@${wind_dir}° (on=${onshore.toFixed(1)} long=${longshore.toFixed(1)}) | ` +
        `sst=${sst.toFixed(1)}°C | ` +
        `eff_rain=${effective_rain.toFixed(1)}(rv_flow=${river_flow_equiv.toFixed(1)} rv_fnu=${river_fnu_equiv.toFixed(1)}) | ` +
        `base_ntu=${base_ntu.toFixed(2)} × rain_mult=${rain_mult.toFixed(3)} | ` +
        `wind_adj=${wind_adj.toFixed(2)} sst_adj=${sst_adj.toFixed(2)} | ` +
        `pre_overlay_ntu=${(base_ntu * rain_mult + wind_adj + sst_adj).toFixed(2)} | ` +
        `sat_adj=${sat_adj.toFixed(2)}(age=${cond.satDataAge ?? "n/a"} ntu=${cond.satTurbidity ?? "n/a"}) | ` +
        `rv_fnu_legacy_adj=${river_fnu_adj.toFixed(2)} | ` +
        `final_ntu=${final_ntu.toFixed(2)} → base_score=${ntuToScore(final_ntu)} | ` +
        `current_adj=${current_adj.toFixed(2)}(onshore=${onshore_cur.toFixed(3)} longshore=${longshore_cur.toFixed(3)}) tide_adj=${tide_adj.toFixed(2)} ` +
        `recovery_adj=${recovery_adj.toFixed(2)} webcam_adj=${webcam_adj.toFixed(2)} | ` +
        `FINAL_SCORE=${score} | ` +
        `table.papa=${spotTable.papa} table.ntu_median=${spotTable.ntu_median} ` +
        `river_gauges=${JSON.stringify(spotTable.river?.gauges ?? null)}`
      );
    }

    return new Response(JSON.stringify({
      score,
      predicted_ntu: Math.round(final_ntu * 10) / 10,
      plumeReach,
      factors,
      model: "lookup-v2",
    }), { headers: HEADERS });

  } catch (err) {
    console.error("[score-full] error:", err);
    return new Response(JSON.stringify({
      score: 50, predicted_ntu: null, plumeReach: 0,
      factors: { drivers: ["Error — fallback score"], error: String(err) },
      model: "fallback",
    }), { status: 200, headers: HEADERS });
  }
});
